# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[prod]
[prod.global.parameters]
stack_name = "slack-call-analyzer-prod"

[prod.build.parameters]
cached = true
parallel = true

[prod.validate.parameters]
lint = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "slack-call-analyzer-prod"
s3_prefix = "slack-call-analyzer/prod"
region = "us-east-2"
image_repositories = []
parameter_overrides = "EnvironmentType=prod"  # Add this line

[prod.package.parameters]
resolve_s3 = true

[prod.sync.parameters]
watch = true

[prod.local_start_api.parameters]
warm_containers = "EAGER"

[prod.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev]
[dev.global.parameters]
stack_name = "slack-call-analyzer-dev"

[dev.build.parameters]
cached = true
parallel = true

[dev.validate.parameters]
lint = true

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "slack-call-analyzer-dev"
s3_prefix = "slack-call-analyzer/dev"
region = "us-east-2"
image_repositories = []
parameter_overrides = "EnvironmentType=dev"  # Add this line

[dev.package.parameters]
resolve_s3 = true

[dev.sync.parameters]
watch = true

[dev.local_start_api.parameters]
warm_containers = "EAGER"

[dev.local_start_lambda.parameters]
warm_containers = "EAGER"

