AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-call-analyzer

Parameters:
  EnvironmentType:
    Type: String
    AllowedValues:
      - dev
      - prod

Mappings:
  EnvironmentConfig:
    dev:
      ListRecordingsEndpoint: "https://wlxxj9i0dj.execute-api.us-east-2.amazonaws.com/Prod/list-recordings"
      TranscriptHandlerEndpoint: "https://wlxxj9i0dj.execute-api.us-east-2.amazonaws.com/Prod/transcript-handler"
      DownloadUrlEndpoint: "https://wlxxj9i0dj.execute-api.us-east-2.amazonaws.com/Prod/download-url"
    prod:
      ListRecordingsEndpoint: "https://fpaztvc0r3.execute-api.us-east-2.amazonaws.com/Prod/list-recordings"
      TranscriptHandlerEndpoint: "https://fpaztvc0r3.execute-api.us-east-2.amazonaws.com/Prod/transcript-handler"
      DownloadUrlEndpoint: "https://fpaztvc0r3.execute-api.us-east-2.amazonaws.com/Prod/download-url"

Resources:
  SlackEventCallbackHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/slack-event-callback-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 200
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
        - !Ref TemplateLayer
      Events:
        SlackEventCalllbackHandlerApi:
          Type: Api
          Properties:
            Path: /slack-event-callback
            Method: post
      Environment:
        Variables:
          LIST_RECORDINGS_ENDPOINT:
            !FindInMap [
              EnvironmentConfig,
              !Ref EnvironmentType,
              ListRecordingsEndpoint,
            ]
          TRANSCRIPT_HANDLER_ENDPOINT:
            !FindInMap [
              EnvironmentConfig,
              !Ref EnvironmentType,
              TranscriptHandlerEndpoint,
            ]
          ENVIRONMENT: !Ref EnvironmentType

  SlackBlockActionHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/slack-block-action-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 200
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
        - !Ref TemplateLayer
      Events:
        SlackBlockActionHandlerApi:
          Type: Api
          Properties:
            Path: /slack-block-action
            Method: post
      Environment:
        Variables:
          LIST_RECORDINGS_ENDPOINT:
            !FindInMap [
              EnvironmentConfig,
              !Ref EnvironmentType,
              ListRecordingsEndpoint,
            ]
          TRANSCRIPT_HANDLER_ENDPOINT:
            !FindInMap [
              EnvironmentConfig,
              !Ref EnvironmentType,
              TranscriptHandlerEndpoint,
            ]
          ENVIRONMENT: !Ref EnvironmentType

  TranscriptHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transcript-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 400
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
      Events:
        TranscriptHandlerApi:
          Type: Api
          Properties:
            Path: /transcript-handler
            Method: post
      Environment:
        Variables:
          DOWNLOAD_URL_ENDPOINT:
            !FindInMap [
              EnvironmentConfig,
              !Ref EnvironmentType,
              DownloadUrlEndpoint,
            ]
          ENVIRONMENT: !Ref EnvironmentType

  ZoomHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zoom-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 400
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
      Events:
        ZoomListRecordings:
          Type: Api
          Properties:
            Path: /list-recordings
            Method: get
        ZoomDownloadUrl:
          Type: Api
          Properties:
            Path: /download-url
            Method: post
      Environment:
        Variables:
          ZOOM_ACCOUNT_ID: E0sx9tC3SoCVASxjEDoSTg
          ZOOM_CLIENT_ID: DceCafsiTZKX_zl8uGiBkQ
          ENVIRONMENT: !Ref EnvironmentType

  UtilityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: utility-layer
      ContentUri: layers/utility-layer/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
  TemplateLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: template-layer
      ContentUri: layers/template-layer/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
