AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-smartbot

Resources:
  SlackHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/slack-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 200
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
      Events:
        SlackHandlerApi:
          Type: Api
          Properties:
            Path: /slack-handler
            Method: post
      Environment:
        Variables:
          ZOOM_LIST_RECORDINGS_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/list-recordings
          TRANSCRIPT_HANDLER_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/transcript-handler
          SLACK_EVENT_CALLBACK_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/slack-event-callback
          SLACK_BLOCK_ACTION_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/slack-block-action
          ZOOM_USER_ID: max.henderson@trainicity.com
          SLACK_BOT_TOKEN: xoxb-747234097457-6203590755877-PpzNSph7vaKS10LHoUXl7GSr
  SlackEventCallbackHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/slack-event-callback-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 200
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
      Events:
        SlackEventCalllbackHandlerApi:
          Type: Api
          Properties:
            Path: /slack-event-callback
            Method: post
      Environment:
        Variables:
          ZOOM_LIST_RECORDINGS_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/list-recordings
          TRANSCRIPT_HANDLER_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/transcript-handler
          ZOOM_USER_ID: max.henderson@trainicity.com
          SLACK_BOT_TOKEN: xoxb-747234097457-6203590755877-PpzNSph7vaKS10LHoUXl7GSr
  SlackBlockActionHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/slack-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 200
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
      Events:
        SlackBlockActionHandlerApi:
          Type: Api
          Properties:
            Path: /slack-block-action
            Method: post
      Environment:
        Variables:
          ZOOM_LIST_RECORDINGS_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/list-recordings
          TRANSCRIPT_HANDLER_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/transcript-handler
          ZOOM_USER_ID: max.henderson@trainicity.com
          SLACK_BOT_TOKEN: xoxb-747234097457-6203590755877-PpzNSph7vaKS10LHoUXl7GSr
  TranscriptHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transcript-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 200
      Architectures:
        - x86_64
      Events:
        TranscriptHandlerApi:
          Type: Api
          Properties:
            Path: /transcript-handler
            Method: post
      Environment:
        Variables:
          ZOOM_DOWNLOAD_FILE_ENDPOINT: https://5qlfmqhtg8.execute-api.us-east-2.amazonaws.com/Prod/download-url
  ZoomHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zoom-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 30
      Architectures:
        - x86_64
      Events:
        ZoomListRecordings:
          Type: Api
          Properties:
            Path: /list-recordings
            Method: get
        ZoomDownloadUrl:
          Type: Api
          Properties:
            Path: /download-url
            Method: post
      Environment:
        Variables:
          ZOOM_ACCOUNT_ID: E0sx9tC3SoCVASxjEDoSTg
          ZOOM_CLIENT_ID: DceCafsiTZKX_zl8uGiBkQ
  UtilityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: utility-layer
      ContentUri: utility-layer/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
