AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-call-analyzer
Resources:
  SlackEventCallbackHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/slack-event-callback-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 200
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
        - !Ref TemplateLayer
      Events:
        SlackEventCalllbackHandlerApi:
          Type: Api
          Properties:
            Path: /slack-event-callback
            Method: post
      Environment:
        Variables:
          ZOOM_LIST_RECORDINGS_ENDPOINT: !Ref list_recordings
          TRANSCRIPT_HANDLER_ENDPOINT: !Ref transcript_handler
          ENVIRONMENT: !Ref environment_type
  SlackBlockActionHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/slack-block-action-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 200
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
        - !Ref TemplateLayer
      Events:
        SlackBlockActionHandlerApi:
          Type: Api
          Properties:
            Path: /slack-block-action
            Method: post
      Environment:
        Variables:
          ZOOM_LIST_RECORDINGS_ENDPOINT: !Ref list_recordings
          TRANSCRIPT_HANDLER_ENDPOINT: !Ref transcript_handler
          ENVIRONMENT: !Ref environment_type
  TranscriptHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transcript-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 400
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
      Events:
        TranscriptHandlerApi:
          Type: Api
          Properties:
            Path: /transcript-handler
            Method: post
      Environment:
        Variables:
          ZOOM_DOWNLOAD_FILE_ENDPOINT: !Ref download_url
          ENVIRONMENT: !Ref environment_type
  ZoomHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zoom-handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 400
      Architectures:
        - x86_64
      Layers:
        - !Ref UtilityLayer
      Events:
        ZoomListRecordings:
          Type: Api
          Properties:
            Path: /list-recordings
            Method: get
        ZoomDownloadUrl:
          Type: Api
          Properties:
            Path: /download-url
            Method: post
      Environment:
        Variables:
          ZOOM_ACCOUNT_ID: E0sx9tC3SoCVASxjEDoSTg
          ZOOM_CLIENT_ID: DceCafsiTZKX_zl8uGiBkQ
          ENVIRONMENT: !Ref environment_type
  UtilityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: utility-layer
      ContentUri: layers/utility-layer/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
  TemplateLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: template-layer
      ContentUri: layers/template-layer/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
