// Event Callback Body Schema
const event_callback = {
  token: "ZmUatUvkVhkAoF1pzumgu9Ka",
  team_id: "TMZ6W2VDF",
  api_app_id: "A065VRQ68FQ",
  event: {
    type: "app_home_opened",
    user: "U01TUH9EH5L",
    channel: "D0662CDGT5Z",
    tab: "messages",
    event_ts: "1701545585.062947",
  },
  type: "event_callback",
  event_id: "Ev068ESLUMJ8",
  event_time: 1701545585,
  authorizations: [
    {
      enterprise_id: null,
      team_id: "TMZ6W2VDF",
      user_id: "U065ZHCN7RT",
      is_bot: true,
      is_enterprise_install: false,
    },
  ],
  is_ext_shared_channel: false,
};

const block_actions = {
  type: "block_actions",
  user: {
    id: "U01TUH9EH5L",
    username: "max.henderson",
    name: "max.henderson",
    team_id: "TMZ6W2VDF",
  },
  api_app_id: "A065VRQ68FQ",
  token: "ZmUatUvkVhkAoF1pzumgu9Ka",
  container: { type: "view", view_id: "V06786S4VDZ" },
  trigger_id: "6271072289063.747234097457.3496afc0fc7d534839430b98533d5930",
  team: { id: "TMZ6W2VDF", domain: "trainicityworkspace" },
  enterprise: null,
  is_enterprise_install: false,
  view: {
    id: "V06786S4VDZ",
    team_id: "TMZ6W2VDF",
    type: "home",
    blocks: [[Object]],
    private_metadata: "",
    callback_id: "home_view",
    state: { values: [Object] },
    hash: "1701523261.zfud1prK",
    title: { type: "plain_text", text: "View Title", emoji: true },
    clear_on_close: false,
    notify_on_close: false,
    close: null,
    submit: null,
    previous_view_id: null,
    root_view_id: "V06786S4VDZ",
    app_id: "A065VRQ68FQ",
    external_id: "",
    app_installed_team_id: "TMZ6W2VDF",
    bot_id: "B0662CD2H5H",
  },
  actions: [
    {
      type: "static_select",
      action_id: "select_meeting_type-67yatLIBR7umLed/0d7+2g==",
      block_id: "CFllP",
      selected_option: [Object],
      placeholder: [Object],
      action_ts: "1701612848.563659",
    },
  ],
};
